[package]
name = "ip-asn-lookup-service"
version = "0.1.0"
authors = ["Bryan Gilbert <gilbertw1@gmail.com>"]

[dependencies]
hyper = "0.12"
futures = "0.1" 
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
cidr = "0.0.4"
